/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO
/****** Object:  Database [Mc2_QueryDb]    Script Date: 2/6/2022 8:59:52 AM ******/
CREATE DATABASE [Mc2_QueryDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mc2_QueryDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Mc2_QueryDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mc2_QueryDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Mc2_QueryDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Mc2_QueryDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mc2_QueryDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mc2_QueryDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mc2_QueryDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mc2_QueryDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Mc2_QueryDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mc2_QueryDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET RECOVERY FULL 
GO
ALTER DATABASE [Mc2_QueryDb] SET  MULTI_USER 
GO
ALTER DATABASE [Mc2_QueryDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mc2_QueryDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mc2_QueryDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mc2_QueryDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mc2_QueryDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Mc2_QueryDb', N'ON'
GO
ALTER DATABASE [Mc2_QueryDb] SET QUERY_STORE = OFF
GO
USE [Mc2_QueryDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Mc2_QueryDb]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 2/6/2022 8:59:52 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [varchar](150) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[EmailAddress] [varchar](50) NOT NULL,
	[BankAccountNumber] [varchar](50) NOT NULL,
	[PhoneNumber] [varchar](15) NOT NULL,
	[DateOfBirth] [datetime2](7) NOT NULL,
	[HasConfilict] [bit] NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Mc2_QueryDb] SET  READ_WRITE 
GO



/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO
/****** Object:  Database [Mc2_WriteDb]    Script Date: 2/6/2022 9:00:23 AM ******/
CREATE DATABASE [Mc2_WriteDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mc2_WriteDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Mc2_WriteDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mc2_WriteDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Mc2_WriteDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Mc2_WriteDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mc2_WriteDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mc2_WriteDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mc2_WriteDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mc2_WriteDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Mc2_WriteDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mc2_WriteDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET RECOVERY FULL 
GO
ALTER DATABASE [Mc2_WriteDb] SET  MULTI_USER 
GO
ALTER DATABASE [Mc2_WriteDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mc2_WriteDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mc2_WriteDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mc2_WriteDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mc2_WriteDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Mc2_WriteDb', N'ON'
GO
ALTER DATABASE [Mc2_WriteDb] SET QUERY_STORE = OFF
GO
USE [Mc2_WriteDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Mc2_WriteDb]
GO
/****** Object:  Table [dbo].[EventStore]    Script Date: 2/6/2022 9:00:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventStore](
	[Id] [uniqueidentifier] NOT NULL,
	[AggregateId] [nvarchar](255) NOT NULL,
	[AggregateTypeName] [nvarchar](255) NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
	[Metadata] [nvarchar](max) NULL,
	[Version] [int] NOT NULL,
	[IsSynced] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_EventStore] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Mc2_WriteDb] SET  READ_WRITE 
GO
