version: '3.4'

services:
  mc2.crudtest.presentation.server:
    image: ${DOCKER_REGISTRY-}mc2crudtestpresentationserver
    build:
      context: .
      dockerfile: Mc2.CrudTest.Presentation/Server/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname:  rabbithost
    ports:
          - "5672:5672"
          - "15672:15672"
     

networks:
  some-net:
    driver: bridge
  